# Complete Self-Contained Docker Compose
# Uses single image with everything included

services:
  clyvanta-complete:
    image: vicky3074/clyvanta-complete:latest
    ports:
      - "80:80"
      - "443:443" 
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://clyvanta_user:clyvanta_pass@clyvanta-postgres:5432/clyvanta_db
    restart: unless-stopped
    container_name: clyvanta-complete
    depends_on:
      - clyvanta-postgres
    networks:
      - clyvanta-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  clyvanta-postgres:
    image: postgres:15-alpine
    container_name: clyvanta-postgres
    environment:
      - POSTGRES_DB=clyvanta_db
      - POSTGRES_USER=clyvanta_user
      - POSTGRES_PASSWORD=clyvanta_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - clyvanta-network

volumes:
  postgres_data:

networks:
  clyvanta-network:
    driver: bridge