#cloud-config
# Oracle Cloud Ubuntu 22.04 initialization for Clyvanta deployment

users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ${ssh_public_key}

packages:
  - docker.io
  - docker-compose
  - git
  - curl
  - jq
  - htop
  - ufw
  - fail2ban

runcmd:
  # Configure firewall
  - ufw allow ssh
  - ufw allow 8080/tcp  # Main website
  - ufw allow 4040/tcp  # Webhook server
  - ufw --force enable

  # Configure Docker
  - systemctl enable docker
  - systemctl start docker
  - usermod -aG docker ubuntu

  # Install Docker Compose v2
  - curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose

  # Create project directory
  - mkdir -p /var/www/clyvanta-oracle
  - chown ubuntu:ubuntu /var/www/clyvanta-oracle

  # Configure fail2ban for SSH protection
  - systemctl enable fail2ban
  - systemctl start fail2ban

  # Disable root login
  - sed -i 's/#PermitRootLogin yes/PermitRootLogin no/' /etc/ssh/sshd_config
  - systemctl restart ssh

  # Set timezone
  - timedatectl set-timezone America/Toronto

  # Create deployment ready marker
  - touch /var/log/cloud-init-complete
  - echo "Clyvanta Oracle Cloud server initialization complete" | wall

write_files:
  - path: /etc/fail2ban/jail.local
    content: |
      [sshd]
      enabled = true
      port = ssh
      filter = sshd
      logpath = /var/log/auth.log
      maxretry = 3
      bantime = 3600
      findtime = 600

  - path: /home/ubuntu/.bashrc_custom
    content: |
      # Clyvanta environment shortcuts
      alias dc='docker-compose'
      alias dcl='docker-compose logs -f'
      alias dcp='docker-compose ps'
      alias dcr='docker-compose restart'
      export CLYVANTA_ENV=production
      export CLYVANTA_SERVER=oracle
      
      # Change to project directory
      cd /var/www/clyvanta-oracle 2>/dev/null || true

  - path: /etc/docker/daemon.json
    content: |
      {
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "10m",
          "max-file": "3"
        },
        "live-restore": true
      }

final_message: "Clyvanta Oracle Cloud server is ready for deployment!"