name: Simple Direct Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'both'
        type: choice
        options:
        - staging
        - production
        - both

jobs:
  deploy:
    name: Direct SSH Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: Direct deployment via SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_HOST: ${{ secrets.DROPLET_IP }}
      run: |
        echo "🚀 Direct SSH deployment starting..."
        
        # Setup SSH
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H $SERVER_HOST >> ~/.ssh/known_hosts
        
        # Execute deployment directly on server
        ssh root@$SERVER_HOST << 'EOF'
          echo "🔧 Starting direct deployment..."
          
          # Navigate to project directory
          cd /var/www/clyvanta || cd /root/clyvanta || {
            echo "❌ Could not find project directory"
            exit 1
          }
          
          echo "📂 Working in: $(pwd)"
          
          # Pull latest code
          echo "📥 Pulling latest code..."
          git fetch origin
          git reset --hard origin/main
          
          # Restart webhook service first
          echo "🔧 Restarting webhook service..."
          pkill -f "deploy-webhook" || true
          docker stop clyvanta-webhook 2>/dev/null || true
          docker rm clyvanta-webhook 2>/dev/null || true
          
          if [ -f "docker-compose.webhook.yml" ]; then
            echo "🐳 Starting webhook via Docker Compose..."
            docker-compose -f docker-compose.webhook.yml up -d --build
          else
            echo "📦 Starting webhook manually..."
            nohup node deploy-webhook.js > /var/log/webhook.log 2>&1 &
          fi
          
          sleep 10
          
          # Deploy applications
          if [[ "${{ github.event.inputs.environment }}" == "staging" || "${{ github.event.inputs.environment }}" == "both" ]]; then
            echo "🚀 Deploying to staging..."
            docker-compose -f docker-compose.staging.yml down || true
            docker-compose -f docker-compose.staging.yml up -d --build
          fi
          
          if [[ "${{ github.event.inputs.environment }}" == "production" || "${{ github.event.inputs.environment }}" == "both" ]]; then
            echo "🚀 Deploying to production..."
            docker-compose down || true
            docker-compose up -d --build
          fi
          
          # Test everything
          sleep 30
          echo "🧪 Testing deployments..."
          
          # Test webhook
          if curl -f http://localhost:4040/health 2>/dev/null; then
            echo "✅ Webhook service is working!"
          else
            echo "⚠️ Webhook service may need manual attention"
          fi
          
          # Test environments
          if [[ "${{ github.event.inputs.environment }}" == "staging" || "${{ github.event.inputs.environment }}" == "both" ]]; then
            if curl -f http://localhost:8081 2>/dev/null; then
              echo "✅ Staging is live!"
            else
              echo "❌ Staging deployment failed"
            fi
          fi
          
          if [[ "${{ github.event.inputs.environment }}" == "production" || "${{ github.event.inputs.environment }}" == "both" ]]; then
            if curl -f http://localhost:8080 2>/dev/null; then
              echo "✅ Production is live!"
            else
              echo "❌ Production deployment failed"
            fi
          fi
          
          echo "🎉 Direct deployment completed!"
        EOF
        
    - name: Verify External Access
      run: |
        echo "🔍 Verifying external access..."
        
        if [[ "${{ github.event.inputs.environment }}" == "staging" || "${{ github.event.inputs.environment }}" == "both" ]]; then
          if curl -f http://${{ secrets.DROPLET_IP }}:8081 2>/dev/null; then
            echo "✅ Staging is accessible externally"
          else
            echo "⚠️ Staging may not be accessible externally"
          fi
        fi
        
        if [[ "${{ github.event.inputs.environment }}" == "production" || "${{ github.event.inputs.environment }}" == "both" ]]; then
          if curl -f http://${{ secrets.DROPLET_IP }}:8080 2>/dev/null; then
            echo "✅ Production is accessible externally"
          else
            echo "⚠️ Production may not be accessible externally"
          fi
        fi
        
        if curl -f http://${{ secrets.DROPLET_IP }}:4040/health 2>/dev/null; then
          echo "✅ Webhook service is accessible externally"
        else
          echo "⚠️ Webhook service may not be accessible externally"
        fi